/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;

import javax.swing.GroupLayout;
import javax.swing.GroupLayout.Alignment;
import javax.swing.JFrame;

import Component.Menu;
import Component.PanelBoder;
import javax.swing.JLabel;
import javax.swing.ImageIcon;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;

/**
 *
 * @author DELL
 */
public class ChangePassword extends JFrame {

    /**
     * Creates new form ChangePassword
     */
    public ChangePassword() {
    	addWindowListener(new WindowAdapter() {
    		@Override
    		public void windowClosing(WindowEvent e) {
    			dispose();
    		}
    	});
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
    	setBounds(0, 0, 764, 387);
    	

    	PanelBoder panelBoder1 = new PanelBoder();
        Menu menu = new Menu();
        menu.setBounds(0, 0, 277, 350);
        jLabel1 = new javax.swing.JLabel();
        jLabel1.setBounds(10, 79, 257, 0);
        jTextField1 = new javax.swing.JTextField();
        jTextField1.setBounds(305, 136, 190, 20);
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator1.setBounds(305, 156, 190, 13);
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator2.setBounds(305, 223, 191, 16);
        jLabel3 = new javax.swing.JLabel();
        jLabel3.setBounds(390, 55, 223, 41);
        jLabel2 = new javax.swing.JLabel();
        jLabel2.setBounds(305, 114, 99, 20);
        jLabel4 = new javax.swing.JLabel();
        jLabel4.setBounds(305, 175, 92, 20);
        jLabel5 = new javax.swing.JLabel();
        jLabel5.setBounds(520, 114, 67, 20);
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator3.setBounds(520, 156, 190, 13);
        jLabel6 = new javax.swing.JLabel();
        jLabel6.setBounds(520, 175, 123, 20);
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator4.setBounds(520, 223, 190, 13);
        jPasswordField2 = new javax.swing.JPasswordField();
        jPasswordField2.setBounds(520, 201, 190, 16);
        jPasswordField3 = new javax.swing.JPasswordField();
        jPasswordField3.setBounds(305, 201, 191, 16);
        jPasswordField1 = new javax.swing.JPasswordField();
        jPasswordField1.setBounds(520, 139, 190, 16);
        jButton1 = new javax.swing.JButton();
        jButton1.setBounds(518, 247, 192, 36);
        jButton2 = new javax.swing.JButton();
        jButton2.setBounds(305, 247, 195, 36);

//        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelBoder1.setOpaque(true);

        jLabel1.setIcon(new javax.swing.ImageIcon("D:\\FPT_Polytechnic\\FALL_2023\\BLOCK2\\DuAn1\\HotelManagement\\src\\main\\resource\\icon\\logo2.png"));

        jTextField1.setBackground(new java.awt.Color(255, 255, 255));
        jTextField1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(0, 77, 247));
        jTextField1.setBorder(null);
        jTextField1.setSelectedTextColor(new java.awt.Color(75, 110, 175));
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jSeparator1.setForeground(new java.awt.Color(51, 51, 255));
        jSeparator1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        jSeparator2.setForeground(new java.awt.Color(51, 51, 255));
        jSeparator2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 77, 247));
        jLabel3.setText("ĐỔI MẬT KHẨU");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 77, 247));
        jLabel2.setText("Tên đăng nhập");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 77, 247));
        jLabel4.setText("Mật khẩu mới");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 77, 247));
        jLabel5.setText("Mật khẩu ");

        jSeparator3.setForeground(new java.awt.Color(51, 51, 255));
        jSeparator3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 77, 247));
        jLabel6.setText("Mật khẩu xác thực");

        jSeparator4.setForeground(new java.awt.Color(51, 51, 255));
        jSeparator4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        jPasswordField2.setBackground(new java.awt.Color(255, 255, 255));
        jPasswordField2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jPasswordField2.setForeground(new java.awt.Color(0, 77, 247));
        jPasswordField2.setText("jPasswordField2");
        jPasswordField2.setBorder(null);

        jPasswordField3.setBackground(new java.awt.Color(255, 255, 255));
        jPasswordField3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jPasswordField3.setForeground(new java.awt.Color(0, 77, 247));
        jPasswordField3.setText("jPasswordField3");
        jPasswordField3.setBorder(null);
        jPasswordField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField3ActionPerformed(evt);
            }
        });
        getContentPane().setBounds(0, 0, 730, 371);

        jPasswordField1.setBackground(new java.awt.Color(255, 255, 255));
        jPasswordField1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jPasswordField1.setForeground(new java.awt.Color(0, 77, 247));
        jPasswordField1.setText("jPasswordField1");
        jPasswordField1.setBorder(null);

        jButton1.setBackground(new java.awt.Color(0, 77, 247));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new ImageIcon(ChangePassword.class.getResource("/Icon/cancel.png"))); // NOI18N
        jButton1.setText("HỦY BỎ");
        jButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));

        jButton2.setBackground(new java.awt.Color(0, 77, 247));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setIcon(new ImageIcon(ChangePassword.class.getResource("/Icon/check.png"))); // NOI18N
        jButton2.setText("ĐỒNG Ý");
        jButton2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        panelBoder1.add(menu);
        panelBoder1.add(jLabel2);
        panelBoder1.add(jTextField1);
        panelBoder1.add(jSeparator1);
        panelBoder1.add(jSeparator3);
        panelBoder1.add(jLabel5);
        panelBoder1.add(jPasswordField1);
        panelBoder1.add(jSeparator2);
        panelBoder1.add(jLabel4);
        panelBoder1.add(jPasswordField3);
        panelBoder1.add(jPasswordField2);
        panelBoder1.add(jSeparator4);
        panelBoder1.add(jLabel6);
        panelBoder1.add(jButton2);
        panelBoder1.add(jButton1);
        panelBoder1.add(jLabel3);
        GroupLayout groupLayout = new GroupLayout(getContentPane());
        groupLayout.setHorizontalGroup(
        	groupLayout.createParallelGroup(Alignment.LEADING)
        		.addGroup(groupLayout.createSequentialGroup()
        			.addComponent(panelBoder1, GroupLayout.DEFAULT_SIZE, 752, Short.MAX_VALUE)
        			.addContainerGap())
        );
        groupLayout.setVerticalGroup(
        	groupLayout.createParallelGroup(Alignment.LEADING)
        		.addGroup(groupLayout.createSequentialGroup()
        			.addComponent(panelBoder1, GroupLayout.PREFERRED_SIZE, 356, GroupLayout.PREFERRED_SIZE)
        			.addContainerGap(172, Short.MAX_VALUE))
        );
        panelBoder1.setLayout(null);
        panelBoder1.add(menu);
        menu.setLayout(null);
        menu.add(jLabel1);
        
        lblNewLabel = new JLabel("");
        lblNewLabel.setIcon(new ImageIcon(ChangePassword.class.getResource("/Icon/logo2.png")));
        lblNewLabel.setBounds(0, 0, 277, 350);
        menu.add(lblNewLabel);
        panelBoder1.add(jLabel2);
        panelBoder1.add(jTextField1);
        panelBoder1.add(jSeparator1);
        panelBoder1.add(jSeparator3);
        panelBoder1.add(jLabel5);
        panelBoder1.add(jPasswordField1);
        panelBoder1.add(jSeparator2);
        panelBoder1.add(jLabel4);
        panelBoder1.add(jPasswordField3);
        panelBoder1.add(jPasswordField2);
        panelBoder1.add(jSeparator4);
        panelBoder1.add(jLabel6);
        panelBoder1.add(jButton2);
        panelBoder1.add(jButton1);
        panelBoder1.add(jLabel3);
        
//        getContentPane().setLayout(groupLayout);

//        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jPasswordField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChangePassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChangePassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChangePassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChangePassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChangePassword().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JPasswordField jPasswordField3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTextField jTextField1;
    private Menu menu1;
    private PanelBoder panelBoder1;
    private JLabel lblNewLabel;
    // End of variables declaration//GEN-END:variables
}
