/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;

import java.io.File;
import java.io.IOException;
import java.lang.System.Logger.Level;
import java.util.Date;

import javax.swing.ImageIcon;

import org.apache.log4j.Logger;
import org.apache.log4j.PropertyConfigurator;

import DAO.TaiKhoanDAO;
import Entity.TaiKhoan;
import Utils.Auth;
import Utils.MsgBox;
import Utils.Validate;
import Utils.XFile;

/**
 *
 * @author DELL
 */
public class LoginFrame extends javax.swing.JFrame {

	private int loginAttempts = 0;
	long timeSinceLastFailedLogin;
	private Date lastFailedLogin;
	public static final Logger logger = Logger.getLogger(LoginFrame.class);

	/**
	 * Creates new form LoginFrame
	 */
	public LoginFrame() {
		initComponents();
		setLocationRelativeTo(null);
		PropertyConfigurator.configure("src\\Log\\log4j.properties");
		remember();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		setUndecorated(true);
		panelBoder1 = new Components.PanelBoder();
		menu1 = new Components.Menu();
		jLabel1 = new javax.swing.JLabel();
		txtUserName = new javax.swing.JTextField();
		jSeparator1 = new javax.swing.JSeparator();
		jSeparator2 = new javax.swing.JSeparator();
		lblForgotPass = new javax.swing.JLabel();
		jLabel3 = new javax.swing.JLabel();
		jLabel5 = new javax.swing.JLabel();
		chkSaveLogin = new javax.swing.JCheckBox();
		jLabel6 = new javax.swing.JLabel();
		txtPassWord = new javax.swing.JPasswordField();
		lblTenDangNhap = new javax.swing.JLabel();
		lblMatKhau = new javax.swing.JLabel();
		btnLogin = new Components.Button();
		btnKetThuc = new Components.Button();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		panelBoder1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
		panelBoder1.setOpaque(true);

		jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		jLabel1.setIcon(new ImageIcon(LoginFrame.class.getResource("/Icon/logo2.png"))); // NOI18N
		jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

		javax.swing.GroupLayout menu1Layout = new javax.swing.GroupLayout(menu1);
		menu1.setLayout(menu1Layout);
		menu1Layout.setHorizontalGroup(menu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(menu1Layout
						.createSequentialGroup().addContainerGap().addComponent(jLabel1,
								javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addContainerGap(12, Short.MAX_VALUE)));
		menu1Layout.setVerticalGroup(menu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menu1Layout.createSequentialGroup()
						.addContainerGap(119, Short.MAX_VALUE).addComponent(jLabel1).addGap(113, 113, 113)));

		txtUserName.setBackground(new java.awt.Color(255, 255, 255));
		txtUserName.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
		txtUserName.setForeground(new java.awt.Color(0, 77, 247));
		txtUserName.setBorder(null);
		txtUserName.setSelectedTextColor(new java.awt.Color(75, 110, 175));
		txtUserName.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				txtUserNameActionPerformed(evt);
			}
		});

		jSeparator1.setForeground(new java.awt.Color(51, 51, 255));
		jSeparator1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

		jSeparator2.setForeground(new java.awt.Color(51, 51, 255));
		jSeparator2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

		lblForgotPass.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
		lblForgotPass.setForeground(new java.awt.Color(0, 77, 247));
		lblForgotPass.setText("Quên mật khẩu ?");
		lblForgotPass.addAncestorListener(new javax.swing.event.AncestorListener() {
			public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
				lblForgotPassAncestorAdded(evt);
			}

			public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
			}

			public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
			}
		});
		lblForgotPass.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				lblForgotPassMouseClicked(evt);
			}

			public void mousePressed(java.awt.event.MouseEvent evt) {
				lblForgotPassMousePressed(evt);
			}

			public void mouseReleased(java.awt.event.MouseEvent evt) {
				lblForgotPassMouseReleased(evt);
			}
		});

		jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
		jLabel3.setForeground(new java.awt.Color(0, 77, 247));
		jLabel3.setText("ĐĂNG NHẬP");
		jLabel5.setIcon(new ImageIcon(LoginFrame.class.getResource("/Icon/user.png"))); // NOI18N

		chkSaveLogin.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
		chkSaveLogin.setForeground(new java.awt.Color(0, 77, 247));
		chkSaveLogin.setLabel("Nhớ mật khẩu !");
		chkSaveLogin.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				chkSaveLoginActionPerformed(evt);
			}
		});

		jLabel6.setIcon(new ImageIcon(LoginFrame.class.getResource("/Icon/lock.png"))); // NOI18N

		txtPassWord.setBackground(new java.awt.Color(255, 255, 255));
		txtPassWord.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
		txtPassWord.setForeground(new java.awt.Color(0, 77, 247));
		txtPassWord.setBorder(null);

		lblTenDangNhap.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
		lblTenDangNhap.setForeground(new java.awt.Color(0, 77, 247));
		lblTenDangNhap.setText("Tên đăng nhập");

		lblMatKhau.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
		lblMatKhau.setForeground(new java.awt.Color(0, 77, 247));
		lblMatKhau.setText("Mật khẩu");

		btnLogin.setBackground(new java.awt.Color(0, 77, 247));
		btnLogin.setForeground(new java.awt.Color(255, 255, 255));
		btnLogin.setText("Đăng nhập");
		btnLogin.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
		btnLogin.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnLoginActionPerformed(evt);
			}
		});

		btnKetThuc.setBackground(new java.awt.Color(0, 77, 247));
		btnKetThuc.setForeground(new java.awt.Color(255, 255, 255));
		btnKetThuc.setText("Kết thúc");
		btnKetThuc.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
		btnKetThuc.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnKetThucActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout panelBoder1Layout = new javax.swing.GroupLayout(panelBoder1);
		panelBoder1.setLayout(panelBoder1Layout);
		panelBoder1Layout.setHorizontalGroup(panelBoder1Layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(panelBoder1Layout.createSequentialGroup().addGap(0, 0, 0)
						.addComponent(menu1, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGroup(panelBoder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(panelBoder1Layout.createSequentialGroup().addGroup(panelBoder1Layout
										.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addGroup(panelBoder1Layout.createSequentialGroup().addGap(74, 74, 74)
												.addGroup(panelBoder1Layout
														.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE,
																125, javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(chkSaveLogin))
												.addGap(50, 50, 50).addComponent(btnKetThuc,
														javax.swing.GroupLayout.PREFERRED_SIZE, 125,
														javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGroup(panelBoder1Layout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
												.addGroup(panelBoder1Layout.createSequentialGroup()
														.addPreferredGap(
																javax.swing.LayoutStyle.ComponentPlacement.RELATED)
														.addComponent(lblForgotPass,
																javax.swing.GroupLayout.PREFERRED_SIZE, 104,
																javax.swing.GroupLayout.PREFERRED_SIZE))
												.addGroup(panelBoder1Layout.createSequentialGroup()
														.addGroup(panelBoder1Layout
																.createParallelGroup(
																		javax.swing.GroupLayout.Alignment.LEADING)
																.addGroup(panelBoder1Layout.createSequentialGroup()
																		.addGap(74, 74, 74).addComponent(jLabel5))
																.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
																		panelBoder1Layout.createSequentialGroup()
																				.addPreferredGap(
																						javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																				.addComponent(jLabel6)))
														.addGap(18, 18, 18)
														.addGroup(panelBoder1Layout
																.createParallelGroup(
																		javax.swing.GroupLayout.Alignment.LEADING,
																		false)
																.addComponent(txtUserName,
																		javax.swing.GroupLayout.PREFERRED_SIZE, 216,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																.addComponent(lblTenDangNhap).addComponent(lblMatKhau)
																.addComponent(txtPassWord,
																		javax.swing.GroupLayout.PREFERRED_SIZE, 235,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																.addComponent(jSeparator1,
																		javax.swing.GroupLayout.DEFAULT_SIZE, 247,
																		Short.MAX_VALUE)
																.addComponent(jSeparator2)))))
										.addContainerGap(52, Short.MAX_VALUE))
								.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
										panelBoder1Layout.createSequentialGroup()
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
														javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
												.addComponent(jLabel3).addGap(74, 74, 74)))));
		panelBoder1Layout.setVerticalGroup(panelBoder1Layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(panelBoder1Layout.createSequentialGroup().addGap(48, 48, 48).addComponent(jLabel3)
						.addGap(35, 35, 35).addComponent(lblTenDangNhap)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addGroup(panelBoder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(panelBoder1Layout.createSequentialGroup()
										.addComponent(txtUserName, javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 23,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(12, 12, 12).addComponent(lblMatKhau))
								.addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 35,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addGroup(panelBoder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(jLabel6)
								.addGroup(panelBoder1Layout.createSequentialGroup()
										.addComponent(txtPassWord, javax.swing.GroupLayout.PREFERRED_SIZE, 20,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 16,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addGroup(panelBoder1Layout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(lblForgotPass).addComponent(chkSaveLogin))))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
								javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addGroup(panelBoder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(btnKetThuc, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGap(35, 35, 35))
				.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
						panelBoder1Layout.createSequentialGroup()
								.addComponent(menu1, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGap(0, 0, Short.MAX_VALUE)));

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup()
						.addComponent(panelBoder1, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(0, 0, Short.MAX_VALUE)));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup()
						.addComponent(panelBoder1, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(0, 0, Short.MAX_VALUE)));

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void txtUserNameActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txtUserNameActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_txtUserNameActionPerformed

	private void lblForgotPassAncestorAdded(javax.swing.event.AncestorEvent evt) {// GEN-FIRST:event_lblForgotPassAncestorAdded
		// TODO add your handling code here:
	}// GEN-LAST:event_lblForgotPassAncestorAdded

	private void lblForgotPassMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_lblForgotPassMouseClicked
		ForgotPassJFrame fg = new ForgotPassJFrame();
		fg.setVisible(true);
	}// GEN-LAST:event_lblForgotPassMouseClicked

	private void lblForgotPassMousePressed(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_lblForgotPassMousePressed

	}// GEN-LAST:event_lblForgotPassMousePressed

	private void lblForgotPassMouseReleased(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_lblForgotPassMouseReleased

	}// GEN-LAST:event_lblForgotPassMouseReleased

	private void chkSaveLoginActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_chkSaveLoginActionPerformed

	}// GEN-LAST:event_chkSaveLoginActionPerformed

	private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnLoginActionPerformed
		dangNhap();
	}// GEN-LAST:event_btnLoginActionPerformed

	private void btnKetThucActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnKetThucActionPerformed
		System.exit(0);
	}// GEN-LAST:event_btnKetThucActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
		// (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
		 * look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Windows".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		}
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new LoginFrame().setVisible(true);
			}
		});
	}

	private void remember() {
		try {
			txtUserName.setText((String) XFile.readObject("user.txt"));
			txtPassWord.setText((String) XFile.readObject("pass.txt"));
			if (txtUserName.getText().length() != 0) {
				chkSaveLogin.setSelected(true);
			}
		} catch (Exception e) {
		}
	}

	private void dangNhap() {
		if (canLogin()) {
			String manv = txtUserName.getText();
			String matKhau = new String(txtPassWord.getPassword());

			try {
				TaiKhoan dao = new TaiKhoanDAO().selectByID(manv);
				if (Validate.isTxtEmpty(manv) || Validate.isTxtEmpty(matKhau)) {
					MsgBox.alert(this, "Vui lòng nhập tài khoản và mật khẩu");

				}
//				else if (!manv.equals(dao.getTenTaiKhoan())) {
//					MsgBox.alert(this, "Sai tên tài khoản");
//					logger.warn(manv + "Sai tên tài khoản");
//				} 
				else if (!matKhau.equals(dao.getMatKhau())) {
					loginAttempts++;
					if (loginAttempts > 5) {
						loginAttempts = 1;
						System.out.println(loginAttempts);
					}
					MsgBox.alert(this, "Mật khẩu không đúng!! Bạn còn " + loginAttempts + "/5 đăng nhập.");

					if (loginAttempts == 5) {
						lastFailedLogin = new Date();
					}
				} else {
					Auth.user = dao;
					if (chkSaveLogin.isSelected()) {
						try {
							XFile.writeObject("user.txt", manv);
							XFile.writeObject("pass.txt", matKhau);
						} catch (IOException ex) {

						}
					} else {
						try {
							File file1 = new File("user.txt");
							file1.delete();
							File file2 = new File("pass.txt");
							file2.delete();
						} catch (Exception e) {
						}
					}
					resetLoginAttempts();
//					MsgBox.alert(this, "Đăng nhập thành công");
					logger.info(manv + "vừa đăng nhập vào hệ thống");
					this.dispose();
					if (Auth.user.getMaChucVu() == 1) {
						ManagerMain managermain = new ManagerMain();
						managermain.setVisible(true);

					} else {

						StaffMain staffmain = new StaffMain();
						staffmain.setVisible(true);
					}
				}
			} catch (Exception e) {
//				e.printStackTrace();
				MsgBox.alert(this, "Tài khoản hoặc mật khẩu không đúng!");
			}
		} else {
			long totalMilliseconds = 1 * 60 * 1000 - timeSinceLastFailedLogin;
			long totalSeconds = totalMilliseconds / 1000;
			long minutes = totalSeconds / 60;
			long seconds = totalSeconds % 60;
			MsgBox.alert(this, "Vui lòng đăng nhập sau " + minutes + " phút " + seconds + " giây");
		}

	}

	public boolean canLogin() {
		if (loginAttempts < 5) {
			return true;
		} else {
			// Kiểm tra xem đã qua 5 phút chưa
			Date currentTime = new Date();
			timeSinceLastFailedLogin = currentTime.getTime() - lastFailedLogin.getTime();
			return timeSinceLastFailedLogin >= 1 * 60 * 1000; // 5 phút
		}
	}

	private void resetLoginAttempts() {
		loginAttempts = 0;
		lastFailedLogin = null;
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private Components.Button btnKetThuc;
	private Components.Button btnLogin;
	private javax.swing.JCheckBox chkSaveLogin;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JSeparator jSeparator1;
	private javax.swing.JSeparator jSeparator2;
	private javax.swing.JLabel lblForgotPass;
	private javax.swing.JLabel lblMatKhau;
	private javax.swing.JLabel lblTenDangNhap;
	private Components.Menu menu1;
	private Components.PanelBoder panelBoder1;
	private javax.swing.JPasswordField txtPassWord;
	private javax.swing.JTextField txtUserName;
	// End of variables declaration//GEN-END:variables
}
