/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.List;

import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.table.DefaultTableModel;

import DAO.ThongKeDAO;
import Swing.ScrollBar;

/**
 *
 * @author NAMVAAU
 */
public class PanelStatistical extends javax.swing.JPanel {

	/**
	 * Creates new form Room
	 */
	public PanelStatistical() {
		initComponents();
		// add row table
		spTable.setVerticalScrollBar(new ScrollBar());
		spTable.getVerticalScrollBar().setBackground(Color.WHITE);
		spTable.getViewport().setBackground(Color.WHITE);
		JPanel p = new JPanel();
		p.setBackground(Color.WHITE);
		spTable.setCorner(JScrollPane.UPPER_RIGHT_CORNER, p);
		initTableDoanhThu();
		initComboBox(cbxDoanhThu);
		initComboBox(cbxDichVu);
		initComboBox(cbxKhachHang);
		fillTableDoanhThu();
		fillTableKhachHang();
		fillTableDichVu();
	}

	private void initTableDoanhThu() {
		DefaultTableModel tblModel = (DefaultTableModel) tableDoanhThu.getModel();
		tblModel.setColumnIdentifiers(new String[] { "Tháng", "Doanh Thu" });
	}

	private void initComboBox(JComboBox cbx) {
		DefaultComboBoxModel model = (DefaultComboBoxModel) cbx.getModel();
		model.removeAllElements();
		List<Integer> lst = new ThongKeDAO().selectYears();
		for (Integer year : lst) {
			model.addElement(year);
		}
		cbx.setSelectedIndex(0);
	}

	private void fillTableDoanhThu() {
		DefaultTableModel tblModel = (DefaultTableModel) tableDoanhThu.getModel();
		tblModel.setRowCount(0);
		try {
			int year = (int) cbxDoanhThu.getSelectedItem();
			List<Object[]> lst = new ThongKeDAO().getDoanhThuThang(year);

			for (Object[] objects : lst) {
				tblModel.addRow(objects);
			}
			lblTongDoanhThu.setText(String.valueOf(new ThongKeDAO().tongDoanhThuNam(year)) + " VNĐ");
		} catch (Exception e) {
		}

	}

	private void fillTableKhachHang() {
		DefaultTableModel tblModel = (DefaultTableModel) tableKhachHang.getModel();
		tblModel.setRowCount(0);
		try {
			int year = (int) cbxKhachHang.getSelectedItem();
			List<Object[]> lst = new ThongKeDAO().getThongKeKhachHang(year);

			for (Object[] objects : lst) {
				tblModel.addRow(objects);
			}
			lblTongKhachHang.setText(String.valueOf(new ThongKeDAO().tongKhachHang(year)) + " Khách");
		} catch (Exception e) {
		}

	}

	private void fillTableDichVu() {
		DefaultTableModel tblModel = (DefaultTableModel) tableDichVu.getModel();
		tblModel.setRowCount(0);
		try {
			int year = (int) cbxKhachHang.getSelectedItem();
			List<Object[]> lst = new ThongKeDAO().getThongKeDichVu(year);
			if (lst.isEmpty()) {
				tableDichVu.removeAll();
			}
			for (Object[] objects : lst) {
				tblModel.addRow(objects);
			}
		} catch (Exception e) {
		}

	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jTabbedPane1 = new javax.swing.JTabbedPane();
		jPanel1 = new javax.swing.JPanel();
		spTable = new javax.swing.JScrollPane();
		tableDoanhThu = new Swing.Table();
		jPanel4 = new javax.swing.JPanel();
		cbxDoanhThu = new javax.swing.JComboBox<>();
		jLabel1 = new javax.swing.JLabel();
		lblTongDoanhThu = new javax.swing.JLabel();
		jPanel2 = new javax.swing.JPanel();
		spTable3 = new javax.swing.JScrollPane();
		tableKhachHang = new Swing.Table();
		jPanel9 = new javax.swing.JPanel();
		cbxKhachHang = new javax.swing.JComboBox<>();
		jLabel2 = new javax.swing.JLabel();
		lblTongKhachHang = new javax.swing.JLabel();
		jPanel3 = new javax.swing.JPanel();
		spTable4 = new javax.swing.JScrollPane();
		tableDichVu = new Swing.Table();
		jPanel10 = new javax.swing.JPanel();
		cbxDichVu = new javax.swing.JComboBox<>();

		setBackground(new java.awt.Color(242, 242, 242));

		jPanel1.setBackground(new java.awt.Color(255, 255, 255));

		spTable.setBorder(null);

		spTable.setViewportView(tableDoanhThu);

		jPanel4.setBackground(new java.awt.Color(255, 255, 255));
		jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "NĂM",
				javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION,
				new java.awt.Font("Segoe UI", 1, 14), new java.awt.Color(32, 136, 203))); // NOI18N

		cbxDoanhThu.setBackground(new java.awt.Color(255, 255, 255));
		cbxDoanhThu.setModel(
				new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
		cbxDoanhThu.addActionListener(new ActionListener() {

			@Override
			public void actionPerformed(ActionEvent e) {
				// TODO Auto-generated method stub
				fillTableDoanhThu();
			}
		});

		cbxKhachHang.addActionListener(new ActionListener() {

			@Override
			public void actionPerformed(ActionEvent e) {
				// TODO Auto-generated method stub
				fillTableKhachHang();
			}
		});
		cbxDichVu.addActionListener(new ActionListener() {

			@Override
			public void actionPerformed(ActionEvent e) {
				// TODO Auto-generated method stub
				fillTableDichVu();
			}
		});

		javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
		jPanel4.setLayout(jPanel4Layout);
		jPanel4Layout.setHorizontalGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel4Layout.createSequentialGroup().addContainerGap()
						.addComponent(cbxDoanhThu, 0, 651, Short.MAX_VALUE).addContainerGap()));
		jPanel4Layout.setVerticalGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel4Layout
						.createSequentialGroup().addContainerGap().addComponent(cbxDoanhThu,
								javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addContainerGap(14, Short.MAX_VALUE)));

		jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
		jLabel1.setForeground(new java.awt.Color(32, 136, 203));
		jLabel1.setText("TỔNG DOANH THU:");

		lblTongDoanhThu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
		lblTongDoanhThu.setForeground(new java.awt.Color(32, 136, 203));
		lblTongDoanhThu.setText("100.000.000 VNĐ");

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
						Short.MAX_VALUE)
				.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE).addComponent(jLabel1)
						.addGap(18, 18, 18).addComponent(lblTongDoanhThu).addContainerGap())
				.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addComponent(spTable, javax.swing.GroupLayout.DEFAULT_SIZE, 673, Short.MAX_VALUE)));
		jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup()
						.addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 344, Short.MAX_VALUE)
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(lblTongDoanhThu, javax.swing.GroupLayout.PREFERRED_SIZE, 34,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addContainerGap())
				.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
						javax.swing.GroupLayout.Alignment.TRAILING,
						jPanel1Layout.createSequentialGroup().addContainerGap(86, Short.MAX_VALUE).addComponent(spTable,
								javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGap(48, 48, 48))));

		jTabbedPane1.addTab("Doanh Thu", jPanel1);

		jPanel2.setBackground(new java.awt.Color(255, 255, 255));

		spTable3.setBorder(null);

		tableKhachHang.setModel(new javax.swing.table.DefaultTableModel(new Object[][] {

		}, new String[] { "Mã Khách Hàng", "Tên Khách Hàng", "Ngày Sinh", "CCCD", "Số Điện Thoại", "Email",
				"Ngày Đặt" }) {
			boolean[] canEdit = new boolean[] { false, false, false, false, false, false };

			public boolean isCellEditable(int rowIndex, int columnIndex) {
				return canEdit[columnIndex];
			}
		});
		spTable3.setViewportView(tableKhachHang);

		jPanel9.setBackground(new java.awt.Color(255, 255, 255));
		jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "NĂM",
				javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION,
				new java.awt.Font("Segoe UI", 1, 14), new java.awt.Color(32, 136, 203))); // NOI18N

		cbxKhachHang.setBackground(new java.awt.Color(255, 255, 255));
		cbxKhachHang.setModel(
				new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

		javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
		jPanel9.setLayout(jPanel9Layout);
		jPanel9Layout.setHorizontalGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel9Layout.createSequentialGroup().addContainerGap()
						.addComponent(cbxKhachHang, 0, 651, Short.MAX_VALUE).addContainerGap()));
		jPanel9Layout.setVerticalGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel9Layout
						.createSequentialGroup().addContainerGap().addComponent(cbxKhachHang,
								javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addContainerGap(14, Short.MAX_VALUE)));

		jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
		jLabel2.setForeground(new java.awt.Color(32, 136, 203));
		jLabel2.setText("TỔNG SỐ KHÁCH HÀNG:");

		lblTongKhachHang.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
		lblTongKhachHang.setForeground(new java.awt.Color(32, 136, 203));
		lblTongKhachHang.setText("203");

		javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
		jPanel2.setLayout(jPanel2Layout);
		jPanel2Layout.setHorizontalGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
						Short.MAX_VALUE)
				.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE).addComponent(jLabel2)
						.addGap(18, 18, 18).addComponent(lblTongKhachHang).addContainerGap())
				.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addComponent(spTable3, javax.swing.GroupLayout.DEFAULT_SIZE, 673, Short.MAX_VALUE)));
		jPanel2Layout.setVerticalGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel2Layout.createSequentialGroup()
						.addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 344, Short.MAX_VALUE)
						.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 34,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(lblTongKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, 34,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addContainerGap())
				.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
						javax.swing.GroupLayout.Alignment.TRAILING,
						jPanel2Layout.createSequentialGroup().addContainerGap(86, Short.MAX_VALUE)
								.addComponent(spTable3, javax.swing.GroupLayout.PREFERRED_SIZE, 330,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGap(48, 48, 48))));

		jTabbedPane1.addTab("Khách Hàng", jPanel2);

		jPanel3.setBackground(new java.awt.Color(255, 255, 255));

		spTable4.setBorder(null);

		tableDichVu.setModel(new javax.swing.table.DefaultTableModel(new Object[][] {

		}, new String[] { "Mã Dịch Vụ", "Tên Dịch Vụ", "Đã Sử Dụng" }) {
			boolean[] canEdit = new boolean[] { false, false, false, false };

			public boolean isCellEditable(int rowIndex, int columnIndex) {
				return canEdit[columnIndex];
			}
		});
		spTable4.setViewportView(tableDichVu);

		jPanel10.setBackground(new java.awt.Color(255, 255, 255));
		jPanel10.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "NĂM",
				javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION,
				new java.awt.Font("Segoe UI", 1, 14), new java.awt.Color(32, 136, 203))); // NOI18N

		cbxDichVu.setBackground(new java.awt.Color(255, 255, 255));
		cbxDichVu.setModel(
				new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

		javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
		jPanel10.setLayout(jPanel10Layout);
		jPanel10Layout.setHorizontalGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel10Layout.createSequentialGroup().addContainerGap()
						.addComponent(cbxDichVu, 0, 651, Short.MAX_VALUE).addContainerGap()));
		jPanel10Layout.setVerticalGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel10Layout
						.createSequentialGroup().addContainerGap().addComponent(cbxDichVu,
								javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addContainerGap(14, Short.MAX_VALUE)));

		javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
		jPanel3.setLayout(jPanel3Layout);
		jPanel3Layout.setHorizontalGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
						Short.MAX_VALUE)
				.addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addComponent(spTable4, javax.swing.GroupLayout.DEFAULT_SIZE, 673, Short.MAX_VALUE)));
		jPanel3Layout.setVerticalGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel3Layout.createSequentialGroup()
						.addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addContainerGap(384, Short.MAX_VALUE))
				.addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
						javax.swing.GroupLayout.Alignment.TRAILING,
						jPanel3Layout.createSequentialGroup().addGap(0, 86, Short.MAX_VALUE).addComponent(spTable4,
								javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE))));

		jTabbedPane1.addTab("Dịch Vụ", jPanel3);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
		this.setLayout(layout);
		layout.setHorizontalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(jTabbedPane1));
		layout.setVerticalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(jTabbedPane1));
	}// </editor-fold>//GEN-END:initComponents

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JComboBox<String> cbxDichVu;
	private javax.swing.JComboBox<String> cbxDoanhThu;
	private javax.swing.JComboBox<String> cbxKhachHang;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPanel jPanel10;
	private javax.swing.JPanel jPanel2;
	private javax.swing.JPanel jPanel3;
	private javax.swing.JPanel jPanel4;
	private javax.swing.JPanel jPanel9;
	private javax.swing.JTabbedPane jTabbedPane1;
	private javax.swing.JLabel lblTongDoanhThu;
	private javax.swing.JLabel lblTongKhachHang;
	private javax.swing.JScrollPane spTable;
	private javax.swing.JScrollPane spTable3;
	private javax.swing.JScrollPane spTable4;
	private Swing.Table tableDichVu;
	private Swing.Table tableDoanhThu;
	private Swing.Table tableKhachHang;
	// End of variables declaration//GEN-END:variables
}
